parameters:
#    utilidad.example.class: Club\UtilidadBundle\Example

services:
#    utilidad.example:
#        class: %utilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
