admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

utilidad:
    resource: "@UtilidadBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

clubs:
    resource: "@ClubsBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    path: /
    defaults: { _controller: ClubsBundle:Sitio:estatica, pagina: 'ayuda' }

#_paginas_estaticas:
#    resource: routing_paginas.yml
#    prefix: /sitio
#    defaults: { _controller: FrameworkBundle:Template:template }
#
#pagina_estatica:
#    path: /sitio/{pagina}
#    defaults: { _controller: ClubsBundle:Sitio:estatica }

#pagina_ayuda:
#    path: /ayuda
#    defaults: { _controller: ClubsBundle:default:ayuda }
