<?php

namespace Club\ClubsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostoCategoriaDisiplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostoCategoriaDisiplinaRepository extends EntityRepository
{
}
